version: '3.1'
services:
  nodejs:
    build: ./NodeJS
    ports:
     - "8123:8123"
    depends_on:
     - dbsql
    environment:
     - DATABASE_HOST=dbsql
    volumes:
     - ./NodeJS/api:/app/api
  dbsql:
    build: ./DB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
